from setuptools import setup, find_packages

setup(
    name='AURA-agent',
    version='0.1.0',
    packages=find_packages(), 

    install_requires=[
        'Flask',
        'FastAPI',
        'starlette',
        'uvicorn',
        'python-dotenv',
        'requests',
        'transformers',
        'sentence-transformers',
        'torch',
        'numpy',
        'pandas',
        'scikit-learn',
        'prophet',
        'aiofiles',
        'aiokafka',
        'async-timeout',
        'anyio',
        'websockets',
        'cryptography',
        'PyNaCl',
        'bcrypt',
        'python-gnupg',
        'watchdog',
        'psutil',
        'colorama',
        'schedule',              
        'loguru',                
        'tenacity',              
        'tqdm',
        'matplotlib',
        'statsmodels',
        'seaborn',               
        'sympy',
        'pytz',
        'PyYAML',
        'regex',
        'typing_extensions',
        'huggingface-hub',
        'safetensors',
        'fsspec',
        'joblib',
        'google-genai',
        'setuptools',
        'wheel',
        'gunicorn',              
    ],
    # to change my agent start service endpoint
    entry_points={
        'console_scripts': [
            'aura-agent-start = agent.server:aura_service', 
        ],
    },
    author='Harpreet Singh',
    description='AURA - Autonomous Unified Resource Agent',
    license='unliscensed',
)